// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: body_weight.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBodyWeight = `-- name: CreateBodyWeight :one
INSERT INTO body_weight (user_id, date, weight_kg)
VALUES ($1, $2, $3)
RETURNING id, user_id, date, weight_kg, created_at
`

type CreateBodyWeightParams struct {
	UserID   pgtype.Int4    `db:"user_id" json:"user_id"`
	Date     pgtype.Date    `db:"date" json:"date"`
	WeightKg pgtype.Numeric `db:"weight_kg" json:"weight_kg"`
}

func (q *Queries) CreateBodyWeight(ctx context.Context, arg CreateBodyWeightParams) (BodyWeight, error) {
	row := q.db.QueryRow(ctx, createBodyWeight, arg.UserID, arg.Date, arg.WeightKg)
	var i BodyWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const getBodyWeightHistory = `-- name: GetBodyWeightHistory :many
SELECT id, user_id, date, weight_kg, created_at FROM body_weight
WHERE user_id = $1
ORDER BY date ASC
`

func (q *Queries) GetBodyWeightHistory(ctx context.Context, userID pgtype.Int4) ([]BodyWeight, error) {
	rows, err := q.db.Query(ctx, getBodyWeightHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyWeight{}
	for rows.Next() {
		var i BodyWeight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.WeightKg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBodyWeight = `-- name: GetLatestBodyWeight :one
SELECT id, user_id, date, weight_kg, created_at FROM body_weight
WHERE user_id = $1
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestBodyWeight(ctx context.Context, userID pgtype.Int4) (BodyWeight, error) {
	row := q.db.QueryRow(ctx, getLatestBodyWeight, userID)
	var i BodyWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}
