// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cardio.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCardioSession = `-- name: CreateCardioSession :one
INSERT INTO cardio_sessions (user_id, date, activity, duration_min, distance_km, calories_burned)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, date, activity, duration_min, distance_km, calories_burned, created_at
`

type CreateCardioSessionParams struct {
	UserID         pgtype.Int4    `db:"user_id" json:"user_id"`
	Date           pgtype.Date    `db:"date" json:"date"`
	Activity       string         `db:"activity" json:"activity"`
	DurationMin    pgtype.Int4    `db:"duration_min" json:"duration_min"`
	DistanceKm     pgtype.Numeric `db:"distance_km" json:"distance_km"`
	CaloriesBurned pgtype.Int4    `db:"calories_burned" json:"calories_burned"`
}

func (q *Queries) CreateCardioSession(ctx context.Context, arg CreateCardioSessionParams) (CardioSession, error) {
	row := q.db.QueryRow(ctx, createCardioSession,
		arg.UserID,
		arg.Date,
		arg.Activity,
		arg.DurationMin,
		arg.DistanceKm,
		arg.CaloriesBurned,
	)
	var i CardioSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Activity,
		&i.DurationMin,
		&i.DistanceKm,
		&i.CaloriesBurned,
		&i.CreatedAt,
	)
	return i, err
}

const getCardioSessionsByDate = `-- name: GetCardioSessionsByDate :many
SELECT id, user_id, date, activity, duration_min, distance_km, calories_burned, created_at FROM cardio_sessions
WHERE user_id = $1 AND date = $2
ORDER BY created_at ASC
`

type GetCardioSessionsByDateParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetCardioSessionsByDate(ctx context.Context, arg GetCardioSessionsByDateParams) ([]CardioSession, error) {
	rows, err := q.db.Query(ctx, getCardioSessionsByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardioSession{}
	for rows.Next() {
		var i CardioSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Activity,
			&i.DurationMin,
			&i.DistanceKm,
			&i.CaloriesBurned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
