// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodEntry = `-- name: CreateFoodEntry :one
INSERT INTO food_entries (user_id, date, meal_type, description, calories, protein_g, carbs_g, fat_g, fiber_g)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, date, meal_type, description, calories, protein_g, carbs_g, fat_g, fiber_g, created_at
`

type CreateFoodEntryParams struct {
	UserID      pgtype.Int4    `db:"user_id" json:"user_id"`
	Date        pgtype.Date    `db:"date" json:"date"`
	MealType    pgtype.Text    `db:"meal_type" json:"meal_type"`
	Description string         `db:"description" json:"description"`
	Calories    int32          `db:"calories" json:"calories"`
	ProteinG    pgtype.Numeric `db:"protein_g" json:"protein_g"`
	CarbsG      pgtype.Numeric `db:"carbs_g" json:"carbs_g"`
	FatG        pgtype.Numeric `db:"fat_g" json:"fat_g"`
	FiberG      pgtype.Numeric `db:"fiber_g" json:"fiber_g"`
}

func (q *Queries) CreateFoodEntry(ctx context.Context, arg CreateFoodEntryParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, createFoodEntry,
		arg.UserID,
		arg.Date,
		arg.MealType,
		arg.Description,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
	)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.Description,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyCalories = `-- name: GetDailyCalories :one
SELECT COALESCE(SUM(calories), 0)::int AS total_calories,
       COALESCE(SUM(protein_g), 0)::decimal AS total_protein,
       COALESCE(SUM(carbs_g), 0)::decimal AS total_carbs,
       COALESCE(SUM(fat_g), 0)::decimal AS total_fat,
       COALESCE(SUM(fiber_g), 0)::decimal AS total_fiber
FROM food_entries
WHERE user_id = $1 AND date = $2
`

type GetDailyCaloriesParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

type GetDailyCaloriesRow struct {
	TotalCalories int32          `db:"total_calories" json:"total_calories"`
	TotalProtein  pgtype.Numeric `db:"total_protein" json:"total_protein"`
	TotalCarbs    pgtype.Numeric `db:"total_carbs" json:"total_carbs"`
	TotalFat      pgtype.Numeric `db:"total_fat" json:"total_fat"`
	TotalFiber    pgtype.Numeric `db:"total_fiber" json:"total_fiber"`
}

func (q *Queries) GetDailyCalories(ctx context.Context, arg GetDailyCaloriesParams) (GetDailyCaloriesRow, error) {
	row := q.db.QueryRow(ctx, getDailyCalories, arg.UserID, arg.Date)
	var i GetDailyCaloriesRow
	err := row.Scan(
		&i.TotalCalories,
		&i.TotalProtein,
		&i.TotalCarbs,
		&i.TotalFat,
		&i.TotalFiber,
	)
	return i, err
}

const getFoodEntriesByDate = `-- name: GetFoodEntriesByDate :many
SELECT id, user_id, date, meal_type, description, calories, protein_g, carbs_g, fat_g, fiber_g, created_at FROM food_entries
WHERE user_id = $1 AND date = $2
ORDER BY created_at ASC
`

type GetFoodEntriesByDateParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetFoodEntriesByDate(ctx context.Context, arg GetFoodEntriesByDateParams) ([]FoodEntry, error) {
	rows, err := q.db.Query(ctx, getFoodEntriesByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodEntry{}
	for rows.Next() {
		var i FoodEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.MealType,
			&i.Description,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyCalories = `-- name: GetMonthlyCalories :many
SELECT date, SUM(calories)::int AS total_calories
FROM food_entries
WHERE user_id = $1
  AND date >= $2::date
  AND date < ($2::date + INTERVAL '1 month')
GROUP BY date
ORDER BY date ASC
`

type GetMonthlyCaloriesParams struct {
	UserID  pgtype.Int4 `db:"user_id" json:"user_id"`
	Column2 pgtype.Date `db:"column_2" json:"column_2"`
}

type GetMonthlyCaloriesRow struct {
	Date          pgtype.Date `db:"date" json:"date"`
	TotalCalories int32       `db:"total_calories" json:"total_calories"`
}

func (q *Queries) GetMonthlyCalories(ctx context.Context, arg GetMonthlyCaloriesParams) ([]GetMonthlyCaloriesRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyCalories, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCaloriesRow{}
	for rows.Next() {
		var i GetMonthlyCaloriesRow
		if err := rows.Scan(&i.Date, &i.TotalCalories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
