// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BodyWeight struct {
	ID        int32              `db:"id" json:"id"`
	UserID    pgtype.Int4        `db:"user_id" json:"user_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	WeightKg  pgtype.Numeric     `db:"weight_kg" json:"weight_kg"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CardioSession struct {
	ID             int32              `db:"id" json:"id"`
	UserID         pgtype.Int4        `db:"user_id" json:"user_id"`
	Date           pgtype.Date        `db:"date" json:"date"`
	Activity       string             `db:"activity" json:"activity"`
	DurationMin    pgtype.Int4        `db:"duration_min" json:"duration_min"`
	DistanceKm     pgtype.Numeric     `db:"distance_km" json:"distance_km"`
	CaloriesBurned pgtype.Int4        `db:"calories_burned" json:"calories_burned"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FoodEntry struct {
	ID          int32              `db:"id" json:"id"`
	UserID      pgtype.Int4        `db:"user_id" json:"user_id"`
	Date        pgtype.Date        `db:"date" json:"date"`
	MealType    pgtype.Text        `db:"meal_type" json:"meal_type"`
	Description string             `db:"description" json:"description"`
	Calories    int32              `db:"calories" json:"calories"`
	ProteinG    pgtype.Numeric     `db:"protein_g" json:"protein_g"`
	CarbsG      pgtype.Numeric     `db:"carbs_g" json:"carbs_g"`
	FatG        pgtype.Numeric     `db:"fat_g" json:"fat_g"`
	FiberG      pgtype.Numeric     `db:"fiber_g" json:"fiber_g"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type StrengthSession struct {
	ID             int32              `db:"id" json:"id"`
	UserID         pgtype.Int4        `db:"user_id" json:"user_id"`
	Date           pgtype.Date        `db:"date" json:"date"`
	ExerciseName   string             `db:"exercise_name" json:"exercise_name"`
	Sets           pgtype.Int4        `db:"sets" json:"sets"`
	Reps           pgtype.Int4        `db:"reps" json:"reps"`
	WeightKg       pgtype.Numeric     `db:"weight_kg" json:"weight_kg"`
	CaloriesBurned pgtype.Int4        `db:"calories_burned" json:"calories_burned"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int32              `db:"id" json:"id"`
	Phone        string             `db:"phone" json:"phone"`
	CalorieGoal  int32              `db:"calorie_goal" json:"calorie_goal"`
	ProteinGoalG pgtype.Int4        `db:"protein_goal_g" json:"protein_goal_g"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WaterLog struct {
	ID        int32              `db:"id" json:"id"`
	UserID    pgtype.Int4        `db:"user_id" json:"user_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	Liters    pgtype.Numeric     `db:"liters" json:"liters"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
