// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strength.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStrengthSession = `-- name: CreateStrengthSession :one
INSERT INTO strength_sessions (user_id, date, exercise_name, sets, reps, weight_kg, calories_burned)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, date, exercise_name, sets, reps, weight_kg, calories_burned, created_at
`

type CreateStrengthSessionParams struct {
	UserID         pgtype.Int4    `db:"user_id" json:"user_id"`
	Date           pgtype.Date    `db:"date" json:"date"`
	ExerciseName   string         `db:"exercise_name" json:"exercise_name"`
	Sets           pgtype.Int4    `db:"sets" json:"sets"`
	Reps           pgtype.Int4    `db:"reps" json:"reps"`
	WeightKg       pgtype.Numeric `db:"weight_kg" json:"weight_kg"`
	CaloriesBurned pgtype.Int4    `db:"calories_burned" json:"calories_burned"`
}

func (q *Queries) CreateStrengthSession(ctx context.Context, arg CreateStrengthSessionParams) (StrengthSession, error) {
	row := q.db.QueryRow(ctx, createStrengthSession,
		arg.UserID,
		arg.Date,
		arg.ExerciseName,
		arg.Sets,
		arg.Reps,
		arg.WeightKg,
		arg.CaloriesBurned,
	)
	var i StrengthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.ExerciseName,
		&i.Sets,
		&i.Reps,
		&i.WeightKg,
		&i.CaloriesBurned,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseHistory = `-- name: GetExerciseHistory :many
SELECT date, MAX(weight_kg) AS max_weight_kg, sets, reps
FROM strength_sessions
WHERE user_id = $1 AND exercise_name = $2
GROUP BY date, sets, reps
ORDER BY date ASC
`

type GetExerciseHistoryParams struct {
	UserID       pgtype.Int4 `db:"user_id" json:"user_id"`
	ExerciseName string      `db:"exercise_name" json:"exercise_name"`
}

type GetExerciseHistoryRow struct {
	Date        pgtype.Date `db:"date" json:"date"`
	MaxWeightKg interface{} `db:"max_weight_kg" json:"max_weight_kg"`
	Sets        pgtype.Int4 `db:"sets" json:"sets"`
	Reps        pgtype.Int4 `db:"reps" json:"reps"`
}

func (q *Queries) GetExerciseHistory(ctx context.Context, arg GetExerciseHistoryParams) ([]GetExerciseHistoryRow, error) {
	rows, err := q.db.Query(ctx, getExerciseHistory, arg.UserID, arg.ExerciseName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExerciseHistoryRow{}
	for rows.Next() {
		var i GetExerciseHistoryRow
		if err := rows.Scan(
			&i.Date,
			&i.MaxWeightKg,
			&i.Sets,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyPRs = `-- name: GetMonthlyPRs :many
SELECT exercise_name,
       DATE_TRUNC('month', date)::date AS month,
       MAX(weight_kg) AS pr_weight_kg
FROM strength_sessions
WHERE user_id = $1
GROUP BY exercise_name, DATE_TRUNC('month', date)
ORDER BY month DESC, exercise_name ASC
`

type GetMonthlyPRsRow struct {
	ExerciseName string      `db:"exercise_name" json:"exercise_name"`
	Month        pgtype.Date `db:"month" json:"month"`
	PrWeightKg   interface{} `db:"pr_weight_kg" json:"pr_weight_kg"`
}

func (q *Queries) GetMonthlyPRs(ctx context.Context, userID pgtype.Int4) ([]GetMonthlyPRsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyPRs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyPRsRow{}
	for rows.Next() {
		var i GetMonthlyPRsRow
		if err := rows.Scan(&i.ExerciseName, &i.Month, &i.PrWeightKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStrengthSessionsByDate = `-- name: GetStrengthSessionsByDate :many
SELECT id, user_id, date, exercise_name, sets, reps, weight_kg, calories_burned, created_at FROM strength_sessions
WHERE user_id = $1 AND date = $2
ORDER BY created_at ASC
`

type GetStrengthSessionsByDateParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetStrengthSessionsByDate(ctx context.Context, arg GetStrengthSessionsByDateParams) ([]StrengthSession, error) {
	rows, err := q.db.Query(ctx, getStrengthSessionsByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StrengthSession{}
	for rows.Next() {
		var i StrengthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.ExerciseName,
			&i.Sets,
			&i.Reps,
			&i.WeightKg,
			&i.CaloriesBurned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT DISTINCT exercise_name FROM strength_sessions
WHERE user_id = $1
ORDER BY exercise_name ASC
`

func (q *Queries) ListExercises(ctx context.Context, userID pgtype.Int4) ([]string, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var exercise_name string
		if err := rows.Scan(&exercise_name); err != nil {
			return nil, err
		}
		items = append(items, exercise_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
