// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (phone)
VALUES ($1)
ON CONFLICT (phone) DO UPDATE SET phone = EXCLUDED.phone
RETURNING id, phone, calorie_goal, protein_goal_g, created_at
`

func (q *Queries) GetOrCreateUser(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CalorieGoal,
		&i.ProteinGoalG,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, calorie_goal, protein_goal_g, created_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CalorieGoal,
		&i.ProteinGoalG,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserGoals = `-- name: UpdateUserGoals :one
UPDATE users
SET calorie_goal = $2, protein_goal_g = $3
WHERE id = $1
RETURNING id, phone, calorie_goal, protein_goal_g, created_at
`

type UpdateUserGoalsParams struct {
	ID           int32       `db:"id" json:"id"`
	CalorieGoal  int32       `db:"calorie_goal" json:"calorie_goal"`
	ProteinGoalG pgtype.Int4 `db:"protein_goal_g" json:"protein_goal_g"`
}

func (q *Queries) UpdateUserGoals(ctx context.Context, arg UpdateUserGoalsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGoals, arg.ID, arg.CalorieGoal, arg.ProteinGoalG)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CalorieGoal,
		&i.ProteinGoalG,
		&i.CreatedAt,
	)
	return i, err
}
