// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: water.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWaterLog = `-- name: CreateWaterLog :one
INSERT INTO water_logs (user_id, date, liters)
VALUES ($1, $2, $3)
RETURNING id, user_id, date, liters, created_at
`

type CreateWaterLogParams struct {
	UserID pgtype.Int4    `db:"user_id" json:"user_id"`
	Date   pgtype.Date    `db:"date" json:"date"`
	Liters pgtype.Numeric `db:"liters" json:"liters"`
}

func (q *Queries) CreateWaterLog(ctx context.Context, arg CreateWaterLogParams) (WaterLog, error) {
	row := q.db.QueryRow(ctx, createWaterLog, arg.UserID, arg.Date, arg.Liters)
	var i WaterLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Liters,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyWater = `-- name: GetDailyWater :one
SELECT COALESCE(SUM(liters), 0)::decimal AS total_liters
FROM water_logs
WHERE user_id = $1 AND date = $2
`

type GetDailyWaterParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetDailyWater(ctx context.Context, arg GetDailyWaterParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getDailyWater, arg.UserID, arg.Date)
	var total_liters pgtype.Numeric
	err := row.Scan(&total_liters)
	return total_liters, err
}

const getWaterLogsByDate = `-- name: GetWaterLogsByDate :many
SELECT id, user_id, date, liters, created_at FROM water_logs
WHERE user_id = $1 AND date = $2
ORDER BY created_at ASC
`

type GetWaterLogsByDateParams struct {
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetWaterLogsByDate(ctx context.Context, arg GetWaterLogsByDateParams) ([]WaterLog, error) {
	rows, err := q.db.Query(ctx, getWaterLogsByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaterLog{}
	for rows.Next() {
		var i WaterLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Liters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
